

services:
  codellama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - codellama

volumes:
  ollama:
